In [1]:
import numpy as np

# how to create an empty and a full numpy array?

In [2]:
a = np.empty((3, 4))
print(a)

[[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
 [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
 [8.45596650e-307 9.34602321e-307 4.94065646e-322 4.93432906e+257]]


# create numpy array filled with all zeros?

In [6]:
a=np.zeros(3)
print(a)

[0. 0. 0.]



# created a numpy array filled with all ones

In [8]:
a = np.ones(2)
a

array([1., 1.])

# created whether a numpy  array contains a specified row

In [9]:

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])


_row = np.array([4, 5, 6])


if any(np.array_equal(row, _row) for row in array):
    print("Specified row is in the array.")
else:
    print("Specified row is not in the array.")


Specified row is in the array.


Original Array:
[[ 1.  2.  3.]
 [ 4. nan  6.]
 [ 7.  8. inf]]

Array after removing rows with non-numeric values:
[[1. 2. 3.]]


In [11]:
a

array([1., 1.])

In [12]:
a.shape

(2,)

In [16]:
b = np.array([[2, 3, 4],[2,4,5]])

In [17]:
b

array([[2, 3, 4],
       [2, 4, 5]])

In [20]:
 
x = np.array([1,2,3,4,5,1,2,1,1,1]) 
print(x) 
print("Most frequent value  array:") 
print(np.bincount(x).argmax())

[1 2 3 4 5 1 2 1 1 1]
Most frequent value  array:
1


In [21]:
import numpy as np


one = np.array([1, 2, 3])


two = np.array([[4, 5, 6],
                          [7, 8, 9]])
combined_array = np.vstack((one, two))
print(combined_array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

_array1, _array2 = np.meshgrid(array1, array2)

combinations = np.vstack((_array1.ravel(), _array2.ravel())).T

print(combinations)


[[1 4]
 [2 4]
 [3 4]
 [1 5]
 [2 5]
 [3 5]
 [1 6]
 [2 6]
 [3 6]]
